[book]
authors = ["zjp"]
language = "zh"
multilingual = false
src = "src"
title = "os-checker book"

[preprocessor.theme]
pagetoc = true
sidebar-width = "180px"

pagetoc-width = "16%"
content-max-width = "86%"
# content-main-margin-left = "4%"
# content-main-margin-right = "15%"
# content-margin-inline-start = "20px"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/os-checker/os-checker"
edit-url-template = "https://github.com/os-checker/book/edit/main/{path}"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

# [output.linkcheck] # Michael-F-Bryan/mdbook-linkcheck

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = true

[output.html.print]
enable = false

[output.theme-ace]
theme-white = "xcode"
theme-dark = "monokai"

