name: Mdbook build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write  # To push a branch 
      pull-requests: write  # To create a PR from that branch
    env:
      MDBOOK_VERSION: '0.4.30' # no sidebar problem (on collapse/auto-focus) in this version
      # MDBOOK_MERMAID_VERSION: '0.13.0'
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
    - name: Install mdbook
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        mkdir ~/tools
        curl -L https://github.com/rust-lang/mdBook/releases/download/v$MDBOOK_VERSION/mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/tools
        # curl -L https://github.com/badboy/mdbook-mermaid/releases/download/v$MDBOOK_MERMAID_VERSION/mdbook-mermaid-v$MDBOOK_MERMAID_VERSION-x86_64-unknown-linux-gnu.tar.gz | tar xz -C ~/tools

        gh release download -R Michael-F-Bryan/mdbook-linkcheck -p mdbook-linkcheck.x86_64-unknown-linux-gnu.zip
        unzip mdbook-linkcheck.x86_64-unknown-linux-gnu.zip -d ~/tools
        chmod +x ~/tools/mdbook-linkcheck

        gh release download -R zjp-CN/mdbook-theme -p mdbook-theme_linux.tar.gz
        tar -xzf mdbook-theme_linux.tar.gz -C ~/tools
        echo ~/tools >> $GITHUB_PATH
    - name: Build 
      run: mdbook build
    - uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        single-commit: true
        branch: gh-pages # The branch the action should deploy to.
        folder: book # The folder the action should deploy.
